import { readdir, readFile, stat } from 'node:fs/promises'
import { join, basename } from 'node:path'
import yaml from 'js-yaml'
import { loadAgentProfile, AgentProfileError } from '../profiles/agent-profile.js'

export interface ProfileListEntry {
  id: string
  description: string | null
  defaultModel: string
  defaultSkills: string[]
  /** True when the YAML loads cleanly. False indicates a malformed profile —
   *  the entry still appears (so the UI can show it as broken) but with
   *  defaultModel/defaultSkills empty. */
  ok: boolean
  /** Error message when ok=false. Helps the operator know why the picker
   *  is showing a profile as broken. */
  error?: string
}

/**
 * List every `*.yaml` in the profile dir. Each entry is loaded through
 * the real resolver (including `extends` merging) so the picker sees
 * what the orchestrator would actually use. Broken profiles surface
 * with `ok: false` rather than being silently dropped.
 */
export async function listAvailableProfiles(dir: string): Promise<ProfileListEntry[]> {
  let files: string[]
  try {
    files = await readdir(dir)
  } catch {
    return []
  }
  const out: ProfileListEntry[] = []
  for (const file of files) {
    if (!file.endsWith('.yaml')) continue
    const id = file.slice(0, -'.yaml'.length)
    try {
      const resolved = await loadAgentProfile(dir, id)
      out.push({
        id: resolved.id,
        description: resolved.description ?? null,
        defaultModel: resolved.defaultModel,
        defaultSkills: resolved.defaultSkills,
        ok: true,
      })
    } catch (err) {
      const message =
        err instanceof AgentProfileError
          ? `${err.code}: ${err.message}`
          : err instanceof Error
            ? err.message
            : String(err)
      out.push({
        id,
        description: null,
        defaultModel: '',
        defaultSkills: [],
        ok: false,
        error: message,
      })
    }
  }
  // Stable order: convention is `_base` first, then alphabetical.
  return out.sort((a, b) => {
    if (a.id === '_base') return -1
    if (b.id === '_base') return 1
    return a.id.localeCompare(b.id)
  })
}

export interface DraftEntry {
  path: string
  /** Source session id if recoverable from frontmatter; null otherwise. */
  sessionId: string | null
  /** ISO timestamp from frontmatter `generated_at` if present. */
  generatedAt: string | null
  /** Title from frontmatter `name` if present, else the path stem. */
  title: string
  /** Rough count of distilled-note H3 entries — gives the UI a "N notes" hint. */
  noteCount: number
  /** File mtime as ISO — newest-first ordering uses this. */
  mtime: string
  bytes: number
}

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---/

/**
 * List every markdown file under `<storageRoot>/wiki/drafts/`. For each,
 * peek at the frontmatter + count H3 sections so the React UI can render
 * a drafts queue without re-reading every file. Sorted newest-mtime first.
 *
 * Drafts are auto-generated by /distill and the auto-distill scheduler;
 * the agent reviews and either promotes entries to canonical wiki pages
 * or lets them age out. Until a cleanup story lands (planning item #5),
 * this list grows unbounded.
 */
export async function listDrafts(storageRoot: string): Promise<DraftEntry[]> {
  const draftsDir = join(storageRoot, 'wiki', 'drafts')
  let files: string[]
  try {
    files = await readdir(draftsDir)
  } catch {
    return []
  }
  const out: DraftEntry[] = []
  for (const file of files) {
    if (!file.endsWith('.md')) continue
    const abs = join(draftsDir, file)
    let content: string
    let st: Awaited<ReturnType<typeof stat>>
    try {
      st = await stat(abs)
      content = await readFile(abs, 'utf-8')
    } catch {
      continue
    }
    const entry = parseDraft(file, content)
    out.push({
      ...entry,
      path: `drafts/${file}`,
      mtime: st.mtime.toISOString(),
      bytes: st.size,
    })
  }
  // Newest-first by mtime.
  out.sort((a, b) => (a.mtime < b.mtime ? 1 : a.mtime > b.mtime ? -1 : 0))
  return out
}

interface PartialDraft {
  sessionId: string | null
  generatedAt: string | null
  title: string
  noteCount: number
}

/**
 * Pull metadata out of a draft's frontmatter + body. Exported for tests
 * so the parsing can be specced without touching the filesystem.
 */
export function parseDraft(filename: string, content: string): PartialDraft {
  const match = content.match(FRONTMATTER_RE)
  let frontmatter: Record<string, unknown> = {}
  let body = content
  if (match) {
    try {
      const parsed = yaml.load(match[1])
      if (parsed && typeof parsed === 'object') {
        frontmatter = parsed as Record<string, unknown>
      }
    } catch {
      // Malformed frontmatter — fall through with empty metadata.
    }
    body = content.slice(match[0].length)
  }
  const sessionId =
    typeof frontmatter.source_session === 'string' ? frontmatter.source_session : null
  // js-yaml's default schema auto-parses ISO date strings into Date
  // objects. Accept either shape so the doc value round-trips cleanly.
  const generatedAt =
    typeof frontmatter.generated_at === 'string'
      ? frontmatter.generated_at
      : frontmatter.generated_at instanceof Date
        ? frontmatter.generated_at.toISOString()
        : null
  const title =
    typeof frontmatter.name === 'string' && frontmatter.name.length > 0
      ? frontmatter.name
      : basename(filename, '.md')
  // ### Note Title — distilled notes use H3 per entry.
  const noteCount = (body.match(/^### /gm) ?? []).length
  return { sessionId, generatedAt, title, noteCount }
}
