-- modules/projects v0.1.0 — initial schema.
-- Every status column uses the uniform enum from the V2 plan
-- (pending | active | blocked | completed | cancelled).
-- metadata_json on every entity row enables the "three-ring" extension model
-- without requiring schema changes.

CREATE TABLE project (
  id TEXT PRIMARY KEY,                       -- ULID generated by service
  number TEXT NOT NULL UNIQUE,               -- operator-facing short id, e.g. '24001'
  name TEXT NOT NULL,
  client TEXT,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'active', 'blocked', 'completed', 'cancelled')),
  folder_path TEXT,                          -- relative path under projects/
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  completed_at INTEGER
);

CREATE INDEX idx_project_status ON project(status, updated_at);

CREATE TABLE phase (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  position INTEGER NOT NULL,                 -- ordering within project; service-assigned
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'active', 'blocked', 'completed', 'cancelled')),
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  completed_at INTEGER
);

CREATE INDEX idx_phase_project ON phase(project_id, position);

CREATE TABLE task (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  phase_id TEXT NOT NULL REFERENCES phase(id) ON DELETE CASCADE,
  parent_task_id TEXT REFERENCES task(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'active', 'blocked', 'completed', 'cancelled')),
  assignee_profile TEXT,                     -- optional agent-profile id
  position INTEGER NOT NULL,                 -- ordering within phase or parent task
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  completed_at INTEGER
);

CREATE INDEX idx_task_phase ON task(phase_id, position);
CREATE INDEX idx_task_project ON task(project_id, status);
CREATE INDEX idx_task_parent ON task(parent_task_id) WHERE parent_task_id IS NOT NULL;

CREATE TABLE task_dependency (
  task_id TEXT NOT NULL REFERENCES task(id) ON DELETE CASCADE,
  depends_on_task_id TEXT NOT NULL REFERENCES task(id) ON DELETE CASCADE,
  PRIMARY KEY (task_id, depends_on_task_id),
  CHECK (task_id != depends_on_task_id)
);

CREATE INDEX idx_task_dependency_target ON task_dependency(depends_on_task_id);
