-- modules/email v0.1.0 — initial schema.
--
-- The `email` table is an INDEX of messages known to AgentOne, not a mirror
-- of the mailbox. Bodies and attachments live in the source until filed.
-- (source_kind, source_id) is unique so re-ingesting the same provider
-- message is a no-op.

CREATE TABLE email (
  id TEXT PRIMARY KEY,                       -- ULID generated by service
  source_kind TEXT NOT NULL,                 -- 'maildir' | 'graph' | ...
  source_id TEXT NOT NULL,                   -- provider-specific message id
  received_at INTEGER NOT NULL,              -- ms epoch
  from_address TEXT NOT NULL,
  from_name TEXT,
  subject TEXT,
  snippet TEXT,                              -- short preview for list rendering
  has_attachments INTEGER NOT NULL DEFAULT 0 CHECK (has_attachments IN (0, 1)),
  is_read INTEGER NOT NULL DEFAULT 0 CHECK (is_read IN (0, 1)),
  filed_project_id TEXT REFERENCES project(id) ON DELETE SET NULL,
  filed_folder_path TEXT,                    -- relative path under <project>/in/
  filed_at INTEGER,
  metadata_json TEXT NOT NULL DEFAULT '{}',  -- to/cc/bcc, headers, source-specific bits
  created_at INTEGER NOT NULL,
  UNIQUE (source_kind, source_id)
);

CREATE INDEX idx_email_received ON email(received_at DESC);
CREATE INDEX idx_email_unread ON email(is_read, received_at DESC);
CREATE INDEX idx_email_filed ON email(filed_project_id, received_at DESC)
  WHERE filed_project_id IS NOT NULL;
